version: '3'

services:
  proxy:
    build:
      context: proxy
    container_name: proxy
    networks:
      - nginx-network
    volumes:
      - ./proxy:/usr/share/nginx/
    ports:
      - "8080:80"
    depends_on:
      - db

  node:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s ./entrypoint.sh
    networks:
      - nginx-network
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-network

networks:
  nginx-network:
    driver: bridge

